ContaOnline/ContaOnline.UI.Web/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ContaOnline.UI.Web.Models
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Senha { get; set; }
        public string Mensagem { get; set; }
    }
}

ContaOnline/ContaOnline.UI.Web/Models/RegistroViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ContaOnline.UI.Web.Models
{
    public class RegistroViewModel
    {
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string ConfirmarSenha { get; set; }


    }
}

ContaOnline/ContaOnline.UI.Web/Controllers/ContaCategoriaController.cs
using ContaOnline.Domain.Interfaces;
using ContaOnline.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContaOnline.UI.Web.Controllers
{
    public class ContaCategoriaController : Controller
    {
        private IContaCategoriaRepository repositorio;
        private Usuario usuario;

        public ContaCategoriaController()
        {
            repositorio = AppHelper.ObterContaCategoriaRepository();
            usuario = AppHelper.ObterUsuarioLogado();
        }

        public ActionResult Inicio()
        {
            if (usuario == null)
            {
                return RedirectToAction("Login", "App");
            }
            var lista = repositorio.ObterTodos(usuario.Id);
            return View(lista);
        }

        public ActionResult Incluir()
        {
            var contaCategoria = new ContaCategoria();
            return View(contaCategoria);
        }

        [HttpPost]
        public ActionResult Incluir(ContaCategoria contaCategoria)
        {
            if (string.IsNullOrEmpty(contaCategoria.Nome))
            {
                ModelState.AddModelError("Nome", "O nome deve ser informado");
            }
            if (ModelState.IsValid)
            {
                contaCategoria.Id = Guid.NewGuid().ToString();
                contaCategoria.UsuarioId = usuario.Id;
                repositorio.Incluir(contaCategoria);
                return RedirectToAction("Inicio");
            }
            return View(contaCategoria);
        }
        public ActionResult Alterar(string Id)
        {
            var contaCategoria = repositorio.ObterPorId(Id);
            return View(contaCategoria);
        }

        [HttpPost]
        public ActionResult Alterar(ContaCategoria contaCategoria)
        {
            if (string.IsNullOrEmpty(contaCategoria.Nome))
            {
                ModelState.AddModelError("Nome", "O nome deve ser informado");
            }
            if (ModelState.IsValid)
            {
                repositorio.Alterar(contaCategoria);
                return RedirectToAction("Inicio");
            }

            return View(contaCategoria);
        }

        public ActionResult Excluir(string Id)
        {
            var contaCategoria = repositorio.ObterPorId(Id);
            return View(contaCategoria);
        }

        [HttpPost]
        public ActionResult Excluir(string Id, FormCollection form)
        {
            repositorio.Excluir(Id);
            return RedirectToAction("Inicio");
        }
    }
}

ContaOnline/ContaOnline.UI.Web/Controllers/ContaController.cs
using ContaOnline.Domain.Interfaces;
using ContaOnline.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContaOnline.UI.Web.Controllers
{
    public class ContaController : Controller
    {
        private IContaRepository repositorio;
        private Usuario usuario;

        public ContaController()
        {
            repositorio = AppHelper.ObterContaRepository();
            usuario = AppHelper.ObterUsuarioLogado();
        }


        public ActionResult Excluir(string id)
        {
            if (usuario == null) return RedirectToAction("Login", "App");
            var conta = repositorio.ObterExibirPorId(id);
            return View(conta);
        }

        [HttpPost]
        public ActionResult Excluir(string id, FormCollection form)
        {
            repositorio.Excluir(id);
            return RedirectToAction("Inicio");
        }

        public ActionResult Alterar(string id)
        {
            if (usuario == null) return RedirectToAction("Login", "App");
            var viewModel = new ContaViewModel();
            viewModel.ContaInstancia = repositorio.ObterPorId(id);
            PreencherViewModel(viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Alterar(ContaViewModel viewModel)
        {
            if (usuario == null) return RedirectToAction("Login", "App");
            try
            {
                viewModel.ContaInstancia.UsuarioId = usuario.Id;
                repositorio.Alterar(viewModel.ContaInstancia);
                return RedirectToAction("Inicio");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            PreencherViewModel(viewModel);
            return View(viewModel);
        }

        public ActionResult Incluir()
        {
            if (usuario == null) return RedirectToAction("Login", "App");
            var viewModel = new ContaViewModel();
            PreencherViewModel(viewModel);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Incluir(ContaViewModel viewModel)
        {
            if (usuario == null) return RedirectToAction("Login", "App");
            try
            {
                viewModel.ContaInstancia.UsuarioId = usuario.Id;
                viewModel.ContaInstancia.Id = Guid.NewGuid().ToString();
                repositorio.Incluir(viewModel.ContaInstancia);
                return RedirectToAction("Inicio");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            PreencherViewModel(viewModel);
            return View(viewModel);
        }

        private void PreencherViewModel(ContaViewModel viewModel)
        {
            var contaCorrenteRep = AppHelper.ObterContaCorrenteRepository();
            viewModel.ContaCorrenteList = contaCorrenteRep.ObterTodos(usuario.Id).ToList();

            var contaCategoriaRep = AppHelper.ObterContaCategoriaRepository();
            viewModel.ContaCategoriaList = contaCategoriaRep.ObterTodos(usuario.Id).ToList();

            var contatoRep = AppHelper.ObterContatoRepository();
            viewModel.ContatoList = contatoRep.ObterTodos(usuario.Id).ToList();

        }

        [HttpPost]
        public ActionResult Inicio(ContaListViewModel viewModel)
        {
            if (usuario == null) return RedirectToAction("Login", "App");

            viewModel.Filtro.UsuarioId = usuario.Id;
            viewModel.ContaList = repositorio.ObterPorFiltro(viewModel.Filtro).ToList();
            PreencherContaListViewModel(viewModel);
            return View(viewModel);

        }

        public ActionResult Inicio()
        {
            if (usuario == null) return RedirectToAction("Login", "App");

            var viewModel = new ContaListViewModel();
            viewModel.Filtro.DataInicial = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            viewModel.Filtro.DataFinal = DateTime.Now;
            viewModel.Filtro.UsuarioId = usuario.Id;
            viewModel.ContaList = repositorio.ObterPorFiltro(viewModel.Filtro).ToList();

            PreencherContaListViewModel(viewModel);

            return View(viewModel);

        }

        private void PreencherContaListViewModel(ContaListViewModel viewModel)
        {
            var catRep = AppHelper.ObterContaCategoriaRepository();
            viewModel.CategoriaList = catRep.ObterTodos(usuario.Id).ToList();

            var contaCorrenteRep = AppHelper.ObterContaCorrenteRepository();
            viewModel.ContaCorrenteList = contaCorrenteRep.ObterTodos(usuario.Id).ToList();

            viewModel.CategoriaList.Insert(0, new ContaCategoria() { Id = string.Empty, Nome = string.Empty });
            viewModel.ContaCorrenteList.Insert(0, new ContaCorrente() { Id = string.Empty, Descricao = string.Empty });
        }
    }
}

ContaOnline/ContaOnline.UI.Web/Controllers/ContaCorrenteController.cs
using ContaOnline.Domain.Interfaces;
using ContaOnline.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContaOnline.UI.Web.Controllers
{
    public class ContaCorrenteController : Controller
    {
        private IContaCorrenteRepository repositorio;
        private Usuario usuario;

        public ContaCorrenteController()
        {
            repositorio = AppHelper.ObterContaCorrenteRepository();
            usuario = AppHelper.ObterUsuarioLogado();
        }
        
        // GET: ContaCorrente
        public ActionResult Inicio()
        {
            if (usuario == null)
            {
                return RedirectToAction("Login", "App");
            }
            var lista = repositorio.ObterTodos(usuario.Id);
            return View(lista);
        }

        public ActionResult Incluir()
        {
            var contaCorrente = new ContaCorrente();
            return View(contaCorrente);
        }

        [HttpPost]
        public ActionResult Incluir(ContaCorrente contaCorrente)
        {
            if (string.IsNullOrEmpty(contaCorrente.Descricao))
            {
                ModelState.AddModelError("Descricao", "A Descrição deve ser informada");
            }
            if (ModelState.IsValid)
            {
                contaCorrente.Id = Guid.NewGuid().ToString();
                contaCorrente.UsuarioId = usuario.Id;
                repositorio.Incluir(contaCorrente);
                return RedirectToAction("Inicio");
            }
            return View(contaCorrente);
        }
        public ActionResult Alterar(string Id)
        {
            var contaCorrente = repositorio.ObterPorId(Id);
            return View(contaCorrente);
        }

        [HttpPost]
        public ActionResult Alterar(ContaCorrente contaCorrente)
        {
            if (string.IsNullOrEmpty(contaCorrente.Descricao))
            {
                ModelState.AddModelError("Descricao", "A Descrição deve ser informada");
            }
            if (ModelState.IsValid)
            {
                repositorio.Alterar(contaCorrente);
                return RedirectToAction("Inicio");
            }
            
            return View(contaCorrente);
        }

        public ActionResult Excluir(string Id)
        {
            var contaCorrente = repositorio.ObterPorId(Id);
            return View(contaCorrente);
        }

        [HttpPost]
        public ActionResult Excluir(string Id, FormCollection form)
        {
            repositorio.Excluir(Id);
            return RedirectToAction("Inicio");
        }
    }
}

ContaOnline/ContaOnline.UI.Web/Controllers/ContatoController.cs
using ContaOnline.Domain.Interfaces;
using ContaOnline.Domain.Models;
using ContaOnline.UI.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContaOnline.UI.Web.Controllers
{
    public class ContatoController : Controller
    {
        private IContatoRepository repositorio;
        private Usuario usuario;
        public ContatoController()
        {
            repositorio = AppHelper.ObterContatoRepository();
            usuario = AppHelper.ObterUsuarioLogado();
        }


        public ActionResult Excluir(string id)
        {
            var contato = repositorio.ObterPorId(id);
            var contatoViewModel = new ContatoViewModel()
            {
                Email = contato.Email,
                Nome = contato.Nome,
                Id = contato.Id,
                Telefone = contato.Telefone
            };
            if (contato is Empresa)
            {
                contatoViewModel.CNPJ = ((Empresa)contato).CNPJ;
                contatoViewModel.Tipo = PessoaFisicaJuridica.PessoaJuridica;
            }

            else
            {
                contatoViewModel.CPF = ((Pessoa)contato).CPF;
                contatoViewModel.RG = ((Pessoa)contato).RG;
                contatoViewModel.DataNascimento = ((Pessoa)contato).DataNascimento;
                contatoViewModel.Tipo = PessoaFisicaJuridica.PessoaFisica;


            }

            return View(contatoViewModel);
        }

        [HttpPost]
        public ActionResult Excluir(string id, FormCollection form)
        {
            repositorio.Excluir(id);
            return RedirectToAction("Inicio");
        }


        public ActionResult Inicio()
        {
            if (usuario == null) return RedirectToAction("Login", "App");
            var lista = repositorio.ObterTodos(usuario.Id);
            return View(lista);
        }

        public ActionResult Alterar(string id)
        {
            var contato = repositorio.ObterPorId(id);
            var contatoViewModel = new ContatoViewModel()
            {
                Email = contato.Email,
                Nome = contato.Nome,
                Id = contato.Id,
                Telefone = contato.Telefone
            };
            if (contato is Empresa)
            {
                contatoViewModel.CNPJ = ((Empresa)contato).CNPJ;
            }

            else
            {
                contatoViewModel.CPF = ((Pessoa)contato).CPF;
                contatoViewModel.RG = ((Pessoa)contato).RG;
                contatoViewModel.DataNascimento = ((Pessoa)contato).DataNascimento;

            }


            return View(contatoViewModel);
        }

        [HttpPost]
        public ActionResult Alterar(ContatoViewModel contatoViewModel)
        {
            if (string.IsNullOrEmpty(contatoViewModel.Nome))
            {
                ModelState.AddModelError("Nome", "O nome deve ser informado");
            }
            if (ModelState.IsValid)
            {
                Contato contato;
                if (contatoViewModel.Tipo == PessoaFisicaJuridica.PessoaFisica)
                {
                    contato = new Pessoa();
                    ((Pessoa)contato).RG = contatoViewModel.RG;
                    ((Pessoa)contato).CPF = contatoViewModel.CPF;
                    ((Pessoa)contato).DataNascimento = contatoViewModel.DataNascimento;
                    contato.Tipo = PessoaFisicaJuridica.PessoaFisica;
                }
                else
                {
                    contato = new Empresa();
                    ((Empresa)contato).CNPJ = contatoViewModel.CNPJ;
                    contato.Tipo = PessoaFisicaJuridica.PessoaJuridica;
                }
                contato.Id = contatoViewModel.Id;
                contato.Nome = contatoViewModel.Nome;
                contato.Telefone = contatoViewModel.Telefone;
                contato.Email = contatoViewModel.Email;
                contato.UsuarioId = usuario.Id;

                repositorio.Alterar(contato);
                return RedirectToAction("Inicio");



            }
            return View(contatoViewModel);
        }

        public ActionResult Incluir()
        {
            var contato = new ContatoViewModel();
            return View(contato);
        }

        [HttpPost]
        public ActionResult Incluir(ContatoViewModel contatoViewModel)
        {
            if (string.IsNullOrEmpty(contatoViewModel.Nome))
            {
                ModelState.AddModelError("Nome", "O nome deve ser informado");
            }
            if (ModelState.IsValid)
            {
                Contato contato;
                if (contatoViewModel.Tipo == PessoaFisicaJuridica.PessoaFisica)
                {
                    contato = new Pessoa();
                    ((Pessoa)contato).RG = contatoViewModel.RG;
                    ((Pessoa)contato).CPF = contatoViewModel.CPF;
                    ((Pessoa)contato).DataNascimento = contatoViewModel.DataNascimento;
                    contato.Tipo = PessoaFisicaJuridica.PessoaFisica;

                }
                else
                {
                    contato = new Empresa();
                    ((Empresa)contato).CNPJ = contatoViewModel.CNPJ;
                    contato.Tipo = PessoaFisicaJuridica.PessoaJuridica;
                }
                contato.Id = Guid.NewGuid().ToString();
                contato.Nome = contatoViewModel.Nome;
                contato.Telefone = contatoViewModel.Telefone;
                contato.Email = contatoViewModel.Email;
                contato.UsuarioId = usuario.Id;

                repositorio.Incluir(contato);
                return RedirectToAction("Inicio");



            }
            return View(contatoViewModel);
        }

    }
}

ContaOnline/ContaOnline.UI.Web/Views/App/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
}

<h2>Conta OnLine</h2>

<p>Bem vindo ao sistema de Contas OnLine</p>

<ul class="list-group">
    <li class="list-group-item">
        <a href='@Url.Action("Inicio", "Conta")'>Contas a Pagar e Receber</a>
    </li>
    <li class="list-group-item">
        <a href='@Url.Action("Inicio", "ContaCorrente")'>Conta Corrente</a>
    </li>
    <li class="list-group-item">
        <a href='@Url.Action("Inicio", "ContaCategoria")'>Categorias de Contas</a>
    </li>
    <li class="list-group-item">
        <a href='@Url.Action("Inicio", "Contato")'>Contato</a>
    </li>
</ul>

ContaOnline/ContaOnline.UI.Web/Views/App/LogOff.cshtml
@{
    ViewBag.Title = "LogOff";
}

<h2>Obrigado por utilizar o Sistema!</h2>

ContaOnline/ContaOnline.UI.Web/Views/App/Login.cshtml
@model ContaOnline.UI.Web.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<hr />

<form method="post">
    <div class="form-horizontal">

        <div class="container">
            <div class="text-danger" id="mensagem">@Model.Mensagem</div>
        </div>
        <div class="form-group">
            <label class="control-label" for="Email">Email:</label>
            <input value="teste@teste.com.br" class="form-control" type="text" name="Email" id="Email" />
        </div>

        <div class="form-group">
            <label class="control-label" for="Senha">Senha:</label>
            <input value="123" class="form-control" type="password" name="Senha" id="Senha" />
        </div>

        <div class="form-group">
            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-send"></span> Enviar</button>
        </div>

    </div>
</form>

ContaOnline/ContaOnline.UI.Web/Views/App/Registro.cshtml
@model ContaOnline.UI.Web.Models.RegistroViewModel

@{
    ViewBag.Title = "Registro";
}
<div class="imagem-fundo">
    <div class="area-cadastro">
        
            <h2 class="h2-registro">Se inscreva e aproveite!</h2>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="cadastro">
                    <div class="form-horizontal">
                        <hr />

                        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.PasswordFor(model => model.Senha, new { @class = "form-control" })

                            </div>
                        </div>
                        <div class="confirmar-senha">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ConfirmarSenha, "Confirmar Senha", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.PasswordFor(model => model.ConfirmarSenha, new { @class = "form-control" })

                                </div>
                            </div>
                        </div>
                        <div class="btn-cadastrar">
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Cadastrar" class="btn btn-default" />
                                </div>
                            </div>
                        </div>

                        <hr />
                    </div>
                </div>
            }       
    </div>
    <div class="area-texto">
        <div class="textos">
            <hr/>
            <h1 class="h1">Conta Online</h1>
            <h2 class="h2">Faça parte do nosso sistema de gestão de contas!</h2>
            <h3 class="h3">Gerencie todas as suas contas e se programe!</h3>
            <div class="paragrafos">
                <h4 class="h4">• Tem dificuldades para organizar qualquer tipo de conta?!</h4>
                <h4 class="h4">• Use nosso sistema de contas online onde você pode transferir qualquer conta para cá e poder organizar cada conta para que você não fique perdido.</h4>
                <h4 class="h4">• E caso tenha duvidas sobre qualquer tipo de conta que pode cadastrar não se preocupe, pois aqui validamos qualquer tipo de conta, boletos, e até faturas.</h4>
                <h4 class="h4-2">• Os primeiros 100 clientes ganham assinatura gratis !</h4>
            </div>
        </div>
    </div>
</div>

ContaOnline/ContaOnline.UI.Web/Views/App/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}

<h2>Sobre este Aplicativo</h2>

<p>Este é um aplicativo para controle de contas a pagar e a receber.</p>